import os
from RandomMelodySite.settings import MIDIFILES_PATH

from mainapp.s3_methods import get_s3_session, BUCKET_NAME

def get_unique_file_name(last_file_name):
        
    file_name = last_file_name.split('.')[0]
    next_number = int(file_name.split("_")[2])+1
    changed_name = file_name.split("_")
    changed_name[-1] = str(next_number)
    new_file_name = "_".join(changed_name)+'.mid'
    return new_file_name


def clean_junk_files():
    """

    Cleans Junk files generated by Anonymous Users - Locally and in S3.

    """

    # Clean Junk From S3
    botoSession = get_s3_session()
    s3 = botoSession.resource('s3')
    bucket = s3.Bucket(BUCKET_NAME)
    anonymous_users_keys = bucket.objects.filter(Prefix="tmpfile")
    anonymous_users_keys.delete()

    # Clean Junk From Local Machine
    
    for file_name in os.listdir(MIDIFILES_PATH):
        if file_name.endswith('.mid'):
            os.remove(os.path.join(MIDIFILES_PATH, file_name))






    """
    if the file looks :
    *   user-name_Randommelody_some-number.mid -> its saved
    *   tmp_user-name_56486413548641_RandomMelody.mid -> not saved, need to delete
    *   tmp_45454554545454_RandomMelody.mid -> need to delete
    """



